apiVersion: v1
kind: Pod
metadata:
  name: tolerations
  labels:
    purpose: "tolerations-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zones: us-east-1d
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "harware" 
    operator: "Equal"   
    value: "gpu"  
    effect: "NoSchedule"
  - key: "harware" 
    operator: "Equal"   
    value: "gpu"  
    effect: "NoExecute"